[webservers]
web-1 ansible_host=89.169.143.159 fqdn=fhm5hr3sf0vbh6ele5qg.auto.internal
web-2 ansible_host=93.77.182.170 fqdn=fhmpkpppm6crmpmfvqca.auto.internal

[databases]
main ansible_host=84.252.131.99 fqdn=fhmdjpq47damfeibel9m.auto.internal
replica ansible_host=111.88.244.132 fqdn=fhmeoe671732kedf7e9g.auto.internal

[storage]
storage ansible_host=111.88.240.200 fqdn=fhm9utk3qpmsncc3rhhk.auto.internal
